FROM node:18

WORKDIR /usr/app

COPY package*.json .

RUN npm install

RUN npm install -g http-server && npm cache clean --force

RUN npm install cors

COPY . .

EXPOSE 3001

CMD ["npm", "start"]
